apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: todo
spec:
  ports:
  - port: 3306
    targetPort: 3306
---
apiVersion: v1
kind: Endpoints
metadata:
  name: mysql
  namespace: todo
subsets:
- addresses:
  - ip: 192.168.122.50
  ports:
  - port: 3306
